name: Matlab

on:
  push:
    branches: [main]
    tags-ignore: ["**"]
    paths:
      - '.github/workflows/matlab.yml'
      - 'c/hv*.[ch]p?p?'
      - 'c/*.mk'
      - 'matlab/Make*'
      - 'matlab/*.[ch]p?p?'
      - 'matlab/*.m'

  pull_request:
    branches:
      - '**'
      - '!gh-pages'
    paths:
      - '.github/workflows/matlab.yml'
      - 'c/hv*.[ch]p?p?'
      - 'c/*.mk'
      - 'matlab/Make*'
      - 'matlab/*.[ch]p?p?'
      - 'matlab/*.m'
  # Manual run
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    name: Build MATLAB code on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04 ]

    steps:
      - uses: actions/checkout@v5

      - name: Install Octave
        run: |
          sudo apt -y install --update --no-install-recommends octave-dev

      - run: make -C matlab test
